In [18]:
# 2 20x20 random matrices

import numpy as np

np.random.seed(0)

matrix1 = np.random.rand(20,20)
matrix2 = np.random.rand(20,20)


def l2_distance(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

print(l2_distance(matrix1, matrix2))

print(l2_distance(np.reshape(matrix1, (20*20)), np.reshape(matrix2, (20*20, 1))))



print(l2_distance(matrix1.T, matrix2.T))


8.186544966134065
165.37557951096954
8.186544966134065


In [2]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
L

5

In [3]:
import re 
s = 'ACBCAC'

re.findall('^AC', s)

['AC']

In [19]:
# a 2d array with the series of numbers from 0 to 35

import numpy as np

array = np.arange(36).reshape(6,6)

print(array)

array[2:4,2:4]

array[[2, 4], [2,4]]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([14, 28])

In [20]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)


[[0 0 1]
 [1 1 1]]
