# Assignment 2

For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```

# NOTES ON THE DATASET

* each column represents a child (look at the SEQNUMC variable which is the unique child ID variable)
* Education of the mother can be divided into categories  less than hs: 1. HS: 2. More than HS: 3. College: 4
* in the dataset the codes 99 and 77 are missing values

In [1]:
import pandas as pd

df = pd.read_csv("NISPUF17.csv")

df.head()

Unnamed: 0  SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  \
0           1   128521     12852     2         NaN  235.916956     1031  2017   
1           2    10741      1074     2         NaN  957.353840     1068  2017   
2           3   220011     22001     2         NaN  189.611299     1050  2017   
3           4    86131      8613     1  675.430817  333.447418     1040  2017   
4           5   227141     22714     1  482.617748  278.768063     1008  2017   

   AGECPOXR  HAD_CPOX  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
0       NaN         2  ...                        NaN      NaN      NaN   
1       NaN         2  ...                        NaN      NaN      NaN   
2       NaN         2  ...                        NaN      NaN      NaN   
3       NaN         2  ...                        NaN      NaN      NaN   
4       NaN         2  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
0      NaN      NaN      NaN          NaN          NaN  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          1.0          2.0  
4      NaN      NaN      NaN          2.0          1.0  

[5 rows x 454 columns]

In [2]:
# Number of columns/variables evaluated for each child
len(df.columns)

454

In [3]:
# How many rows and columns the dataframe has
df.shape

(28465, 454)

In [4]:
len(df["EDUC1"])

28465

In [5]:
#Education of the mother can be divided into categories 1, 2, 3, 4

df["EDUC1"].unique()

array([4, 3, 1, 2], dtype=int64)

In [6]:
len(df[df["EDUC1"] == 1])

2904

In [7]:
total = len(df[df["EDUC1"] == 1]) + len(df[df["EDUC1"] == 2]) + len(df[df["EDUC1"] == 3])+ len(df[df["EDUC1"] == 4])
total



28465

In [8]:
def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE

    
    M1 = len(df[df["EDUC1"] == 1]) #less than highschool
    M2 = len(df[df["EDUC1"] == 2]) # highschool
    M3 = len(df[df["EDUC1"] == 3]) # more than highschool
    M4 = len(df[df["EDUC1"] == 4]) # college

    total = M1+M2+M3+M4

    return  {"less than high school":M1/total,
    "high school":M2/total,
    "more than high school but not college":M3/total,
    "college":M4/total}

    

    
    raise NotImplementedError()

proportion_of_education()

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [9]:
df["EDUC1"].value_counts(normalize=True)
#this code returns a series

4    0.479747
3    0.245881
2    0.172352
1    0.102020
Name: EDUC1, dtype: float64

In [10]:
df["EDUC1"].value_counts(normalize=True).get(1)

0.10202002459160373

In [11]:
# another solution for the same problem is

def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE

    M1 = df["EDUC1"].value_counts(normalize=True).get(1)
    M2 = df["EDUC1"].value_counts(normalize=True).get(2)
    M3 = df["EDUC1"].value_counts(normalize=True).get(3)
    M4 = df["EDUC1"].value_counts(normalize=True).get(4)

    return {"less than high school":M1,
            "high school":M2,   
            "more than high school but not college":M3,
            "college":M4}

    #   df["EDUC1"].value_counts(normalize=True).to_dict()
    raise NotImplementedError()


proportion_of_education()



{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [12]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [13]:
df["P_NUMFLU"]

0        NaN
1        NaN
2        NaN
3        3.0
4        0.0
        ... 
28460    NaN
28461    NaN
28462    NaN
28463    NaN
28464    NaN
Name: P_NUMFLU, Length: 28465, dtype: float64

In [14]:
# kids who got breastfed
# 1 = yes, 2 = no , 77 = don't know, 99 = refused

df["CBF_01"].unique()

array([ 1,  2, 99, 77], dtype=int64)

In [15]:
# So, the whole line of code calculates the mean of the "P_NUMFLU" values for the rows where "CBF_01" is 1.
df[df["CBF_01"] == 1]["P_NUMFLU"].mean()

1.8799187420058687

In [16]:
df[df["CBF_01"] == 2]["P_NUMFLU"].mean()

1.5963945918878317

In [17]:
def average_influenza_doses():
    # YOUR CODE HERE

    # kids who got breastfed
    # 1 = yes, 2 = no , 77 = don't know, 99 = refused

    # So, the whole line of code calculates the mean of the "P_NUMFLU" values for the rows where "CBF_01" is 1.
    YBF = df[df["CBF_01"] == 1]["P_NUMFLU"].mean()
    NBF = df[df["CBF_01"] == 2]["P_NUMFLU"].mean()

    return (YBF, NBF)
    raise NotImplementedError()

average_influenza_doses()

(1.8799187420058687, 1.5963945918878317)

In [18]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."


## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

# The following attempt is right but we didn't discriminate the results by sex

In [32]:
def chickenpox_by_sex():
    
    #contracted chickenpox but where vaccinated against it

    # Calculate the number of children who contracted chickenpox but were vaccinated against it
    contracted_vaccinated = len(df[(df["HAD_CPOX"] == 1) & (df["P_NUMVRC"] >= 1)])

    # Calculate the number of children who were vaccinated but did not contract chickenpox
    vaccinated_not_contracted = len(df[(df["HAD_CPOX"] == 2) & (df["P_NUMVRC"] >= 1)])

    # Calculate the ratio for each sex
    male_ratio = contracted_vaccinated / vaccinated_not_contracted
    female_ratio = contracted_vaccinated / vaccinated_not_contracted

    # Return the results as a dictionary
    return {"male": male_ratio, "female": female_ratio}

    raise NotImplementedError()

chickenpox_by_sex()["male"]

0.008749096167751266

The following is not my attempt but it is right.

In [34]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    import pandas as pd
    
    df = pd.read_csv('NISPUF17.csv')
    
    df = pd.read_csv('NISPUF17.csv', index_col=0)
    df = df[["SEX", "HAD_CPOX", "P_NUMVRC"]].dropna()
    df = df[df["P_NUMVRC"] > 0]
    
    male_df = df[df["SEX"] == 1]
    female_df = df[df["SEX"] == 2]
    
    female_chickenpox = female_df[(female_df["HAD_CPOX"] == 1) & (female_df["P_NUMVRC"] >= 1)]
    female_non_chickenpox = female_df[(female_df["HAD_CPOX"] == 2) & (female_df["P_NUMVRC"] >= 1)]
    
    male_ratio = len(male_df[male_df["HAD_CPOX"] == 1])/len(male_df[male_df["HAD_CPOX"] == 2])
    female_ratio = len(female_df[female_df["HAD_CPOX"] == 1])/len(female_df[female_df["HAD_CPOX"] == 2])
    
    return {"male": male_ratio, "female": female_ratio}

chickenpox_by_sex()["female"]

0.0077918259335489565

I will combine those two into my own solution:

In [38]:
def chickenpox_by_sex():

    # Calculate the number of children who contracted chickenpox but were vaccinated against it
    contracted_vaccinated_male = len(df[(df["HAD_CPOX"] == 1) & (df["P_NUMVRC"] >= 1) & (df["SEX"] == 1)])
    contracted_vaccinated_female = len(df[(df["HAD_CPOX"] == 1) & (df["P_NUMVRC"] >= 1) & (df["SEX"] == 2)])

    # Calculate the number of children who were vaccinated but did not contract chickenpox
    vaccinated_not_contracted_male = len(df[(df["HAD_CPOX"] == 2) & (df["P_NUMVRC"] >= 1) & (df["SEX"] == 1)])
    vaccinated_not_contracted_female = len(df[(df["HAD_CPOX"] == 2) & (df["P_NUMVRC"] >= 1) & (df["SEX"] == 2)])

    # Calculate the ratio for each sex
    male_ratio = contracted_vaccinated_male / vaccinated_not_contracted_male
    female_ratio = contracted_vaccinated_female / vaccinated_not_contracted_female

    # Return the results as a dictionary
    return {"male": male_ratio, "female": female_ratio}

chickenpox_by_sex()["female"]

0.0077918259335489565

In [22]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."


## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [62]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # this is just an example dataframe
    df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
                   "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    #return corr

    # YOUR CODE HERE

    df = pd.read_csv('NISPUF17.csv', index_col=0)

    #df = df[["HAD_CPOX", "P_NUMVRC"]].dropna()
    df = df.dropna(subset=["P_NUMVRC", "HAD_CPOX"])
    df = df[df["HAD_CPOX"] <= 2] # remove rows where HAD_CPOX is 77 or 99 and it's ok to have values of P_NUMVRC equal to 0

    corr, pval = stats.pearsonr(df["HAD_CPOX"], df["P_NUMVRC"])

    return corr
    
    raise NotImplementedError()

corr_chickenpox()

0.07044873460148028

In [47]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."


In [61]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    df = pd.read_csv('NISPUF17.csv', index_col=0)
    df = df[df["HAD_CPOX"] <= 2]
    df = df[~df["P_NUMVRC"].isna() & ~df["HAD_CPOX"].isna()]

    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["HAD_CPOX"], df["P_NUMVRC"])
    
    # just return the correlation
    return corr

corr_chickenpox()

0.07044873460148028

In [55]:
df["P_NUMVRC"].unique()

array([nan,  1.,  0.,  2.,  3.])

In [54]:
df["HAD_CPOX"].unique()

array([ 2,  1, 77, 99], dtype=int64)